// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzZHIh76HG_cWaUyRsQQDdUSJhC3tPCP0',
    appId: '1:917334644935:web:1f31c97a5441f4278506e2',
    messagingSenderId: '917334644935',
    projectId: 'awakening-3b7a9',
    authDomain: 'awakening-3b7a9.firebaseapp.com',
    storageBucket: 'awakening-3b7a9.firebasestorage.app',
    measurementId: 'G-Z5EC3C25NX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Duc_gcD00CNRYjFyA9H9ccspWzPIieY',
    appId: '1:917334644935:android:3628ebccbf160cc78506e2',
    messagingSenderId: '917334644935',
    projectId: 'awakening-3b7a9',
    storageBucket: 'awakening-3b7a9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzZHIh76HG_cWaUyRsQQDdUSJhC3tPCP0',
    appId: '1:917334644935:web:387a184c1ec04b448506e2',
    messagingSenderId: '917334644935',
    projectId: 'awakening-3b7a9',
    authDomain: 'awakening-3b7a9.firebaseapp.com',
    storageBucket: 'awakening-3b7a9.firebasestorage.app',
    measurementId: 'G-7CW7QTL943',
  );
}
