name: Flutter Build & Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.24.3"

      - name: Create .env file
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      # Get flutter dependencies.
      - run: flutter pub get

      # Build apk.
      - run: flutter build apk

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
